const MONSTERS = [
    'Acidic Glavenus', 
    'Alatreon',
    'Ancient Leshen',
    'Anjanath',
    'Azure Rathalos',
    'Banbaro',
    'Barioth',
    'Barroth',
    'Bazelgeuse',
    'Behemoth',
    'Beotodus',
    'Black Diablos',
    'Blackveil Vaal Hazak',
    'Brachydios',
    'Brute Tigrex',
    'Coral Pukei-Pukei',
    'Deviljho',
    'Diablos',
    'Dodogama',
    'Ebony Odogaron',
    'Fatalis',
    'Frostfang Barioth',
    'Fulgur Anjanath',
    'Furious Rajang',
    'Glavenus',
    'Gold Rathian',
    'Great Girros',
    'Great Jagras',
    'Jyuratodus',
    'Kirin',
    'Kulu-Ya-Ku',
    'Kulve Taroth',
    'Kushala Daora',
    'AT Kushala Daora',
    'Lavasioth',
    'Legiana',
    'Leshen',
    'Lunastra',
    'AT Lunastra',
    'Namielle',
    'AT Namielle',
    'Nargacuga',
    'Nergigante',
    'AT Nergigante',
    'Nightshade Paolumu',
    'Odogaron',
    'Paolumu',
    'Pink Rathian',
    'Pukei-Pukei',
    'Radobaan',
    'Raging Brachydios',
    'Rajang',
    'Rathalos',
    'Rathian',
    'Ruiner Nergigante',
    "Safi'jiiva",
    'Savage Deviljho',
    'Scarred Yian Garuga',
    'Seething Bazelgeuse',
    'Shara Ishvalda',
    'Shrieking Legiana',
    'Silver Rathalos',
    'Stygian Zinogre',
    'AT Teostra',
    'Tigrex',
    'Tobi-Kadachi',
    'Tzitzi-Ya-Ku',
    'Uragaan',
    'Vaal Hazak',
    'Velkhana',
    'AT Velkhana',
    'Viper Tobi-Kadachi',
    "Xeno'jiiva",
    'Yian Garuga',
    'Zinogre',
    'Zorah Magdaros'
]

export default MONSTERS